/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author ASUS TUF
 */
public class Main_form extends javax.swing.JFrame {
    int num1,num2;
    String signo;
    /**
     * Creates new form Main_form
     */
    public Main_form() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_info = new javax.swing.JLabel();
        Btn_clear = new javax.swing.JButton();
        Btn_division = new javax.swing.JButton();
        Btn_multi = new javax.swing.JButton();
        Btn_resta = new javax.swing.JButton();
        Btn_nueve = new javax.swing.JButton();
        Btn_ocho = new javax.swing.JButton();
        Btn_siete = new javax.swing.JButton();
        Btn_suma = new javax.swing.JButton();
        Btn_cuatro = new javax.swing.JButton();
        Btn_cinco = new javax.swing.JButton();
        Btn_seis = new javax.swing.JButton();
        Btn_uno = new javax.swing.JButton();
        Btn_2 = new javax.swing.JButton();
        Btn_3 = new javax.swing.JButton();
        Btn_cero = new javax.swing.JButton();
        Btn_igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_info.setBackground(new java.awt.Color(204, 204, 204));
        Lbl_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Lbl_info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lbl_info.setOpaque(true);

        Btn_clear.setText("C");
        Btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_clearActionPerformed(evt);
            }
        });

        Btn_division.setText("/");
        Btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_divisionActionPerformed(evt);
            }
        });

        Btn_multi.setText("X");
        Btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_multiActionPerformed(evt);
            }
        });

        Btn_resta.setText("-");
        Btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_restaActionPerformed(evt);
            }
        });

        Btn_nueve.setText("9");
        Btn_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_nueveActionPerformed(evt);
            }
        });

        Btn_ocho.setText("8");
        Btn_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ochoActionPerformed(evt);
            }
        });

        Btn_siete.setText("7");
        Btn_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sieteActionPerformed(evt);
            }
        });

        Btn_suma.setText("+");
        Btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sumaActionPerformed(evt);
            }
        });

        Btn_cuatro.setText("4");
        Btn_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cuatroActionPerformed(evt);
            }
        });

        Btn_cinco.setText("5");
        Btn_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_cincoActionPerformed(evt);
            }
        });

        Btn_seis.setText("6");
        Btn_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_seisActionPerformed(evt);
            }
        });

        Btn_uno.setText("1");
        Btn_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_unoActionPerformed(evt);
            }
        });

        Btn_2.setText("2");
        Btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });

        Btn_3.setText("3");
        Btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_3ActionPerformed(evt);
            }
        });

        Btn_cero.setText("0");
        Btn_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ceroActionPerformed(evt);
            }
        });

        Btn_igual.setText("=");
        Btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lbl_info, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Btn_cero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Btn_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btn_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Lbl_info, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Btn_suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn_igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ceroActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"0");
    }//GEN-LAST:event_Btn_ceroActionPerformed

    private void Btn_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_unoActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"1");
    }//GEN-LAST:event_Btn_unoActionPerformed

    private void Btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_2ActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"2");
    }//GEN-LAST:event_Btn_2ActionPerformed

    private void Btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_3ActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"3");    }//GEN-LAST:event_Btn_3ActionPerformed

    private void Btn_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cuatroActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"4");
    }//GEN-LAST:event_Btn_cuatroActionPerformed

    private void Btn_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_cincoActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"5");    }//GEN-LAST:event_Btn_cincoActionPerformed

    private void Btn_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_seisActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"6");
    }//GEN-LAST:event_Btn_seisActionPerformed

    private void Btn_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sieteActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"7");
    }//GEN-LAST:event_Btn_sieteActionPerformed

    private void Btn_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ochoActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"8");
    }//GEN-LAST:event_Btn_ochoActionPerformed

    private void Btn_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_nueveActionPerformed
        Lbl_info.setText(Lbl_info.getText()+"9");
    }//GEN-LAST:event_Btn_nueveActionPerformed

    private void Btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_clearActionPerformed
        Lbl_info.setText("");
    }//GEN-LAST:event_Btn_clearActionPerformed

    private void Btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_divisionActionPerformed
        num1 = Integer.parseInt(Lbl_info.getText());
        signo = "/";
        Lbl_info.setText("");
    }//GEN-LAST:event_Btn_divisionActionPerformed

    private void Btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_multiActionPerformed
        num1 = Integer.parseInt(Lbl_info.getText());
        signo = "*";
        Lbl_info.setText("");
    }//GEN-LAST:event_Btn_multiActionPerformed

    private void Btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_restaActionPerformed
        num1 = Integer.parseInt(Lbl_info.getText());
        signo = "-";
        Lbl_info.setText("");
    }//GEN-LAST:event_Btn_restaActionPerformed

    private void Btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sumaActionPerformed
        num1 = Integer.parseInt(Lbl_info.getText());
        signo = "+";
        Lbl_info.setText("");
    }//GEN-LAST:event_Btn_sumaActionPerformed

    private void Btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_igualActionPerformed
        num2 = Integer.parseInt(Lbl_info.getText());
        
        switch(signo){
            case "+":
                Lbl_info.setText(Integer.toString(num1+num2)); 
                break;
            case "-":
                Lbl_info.setText(Integer.toString(num1-num2)); 
                break;
            case "*":
                Lbl_info.setText(Integer.toString(num1*num2)); 
                break;
            case "/":
                Lbl_info.setText(Integer.toString(num1/num2)); 
                break;
        }
    }//GEN-LAST:event_Btn_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_2;
    private javax.swing.JButton Btn_3;
    private javax.swing.JButton Btn_cero;
    private javax.swing.JButton Btn_cinco;
    private javax.swing.JButton Btn_clear;
    private javax.swing.JButton Btn_cuatro;
    private javax.swing.JButton Btn_division;
    private javax.swing.JButton Btn_igual;
    private javax.swing.JButton Btn_multi;
    private javax.swing.JButton Btn_nueve;
    private javax.swing.JButton Btn_ocho;
    private javax.swing.JButton Btn_resta;
    private javax.swing.JButton Btn_seis;
    private javax.swing.JButton Btn_siete;
    private javax.swing.JButton Btn_suma;
    private javax.swing.JButton Btn_uno;
    private javax.swing.JLabel Lbl_info;
    // End of variables declaration//GEN-END:variables
}
